[profile.default]
via_ir = true
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]
# [rpc_endpoints]
# sepolia = "${SEPOLIA_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_KEY}" ,chain=11155111,url="https://eth-sepolia.public.blastapi.io" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
